### ISSUE TITLE
Bug(s) in indexing worksheets

### ISSUE THREAD

**Issue by sanmai-NL** [tafia/calamine#114]
#113 contains code aimed at debugging indexing bugs.

```rust
let range = workbook.worksheet_range(name_worksheet.as_str());
if range.is_empty() {
    continue
}
let (row_max, col_max) = (row_max_usize as u32, col_max_usize as u32);
trace!("{}x{} matrix", row_max, col_max);
for index_col in 0..col_max {
    for index_row in 0..row_max {
        // panics
        let cell = range.get_value((index_row, index_col));
    }
}
```

**Comment by sanmai-NL** [comment]
# Empty worksheet considered 1x1
```
TRACE 2018-02-04T14:34:21Z: calamine_debug: 1x1 matrix
thread 'calamine_debug::tests::xls_1' panicked at 'assertion failed: self.inner.len() > 0', calamine/src/lib.rs:411:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:537
   6: <calamine::Range<T>>::get_value
             at 
<panic macros>:3
   7: calamine_debug::n_personaldatum_from_reader
             at src/personaldatum/semistructured.rs:100
```

**Comment by sanmai-NL** [comment]
## Column 0 not accessible in 30x6 worksheet

```
TRACE 2018-02-04T14:34:21Z: calamine_debug: 30x6 matrix
thread 'calamine_debug::tests::xls_3' panicked at '0 - 1 is out of bounds.', calamine/src/lib.rs:413:87
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: <calamine::Range<T>>::get_value::{{closure}}
             at <panic macros>:7
   8: <core::option::Option<T>>::unwrap_or_else
             at /checkout/src/libcore/option.rs:376
   9: <calamine::Range<T>>::get_value
             at calamine/src/lib.rs:413
```

**Comment by sanmai-NL** [comment]
There are two instances of each of these bugs, with different files.

**Comment by sanmai-NL** [comment]
@tafia: Do you have a time planning for looking into this, perhaps? 🙂

**Comment by tafia** [comment]
I unfortunately can't do much until end of February I'll try my best before
but it is really not sure.
Hope you understand.

**Comment by tafia** [comment]
Ok I am back now!
From you analysis where do you think the root cause is:
1. a logic error when indexing
2. a missing fault tolerant logic implementation (something like clamp mechanism)
3. a parsing issue
4. a corrupted file

**Comment by sanmai-NL** [comment]
I assume it is 1/2. I had looked at some Calamine code and the way it calculated indexes was a bit off here and there. I fixed that provisionally, but lost that code. Anyway, the fix did not solve a fundamental problem in getting the max. row and column index.
