### ISSUE TITLE
range end index 2 out of range for slice of length 0

### ISSUE THREAD

**Issue by 1991766703** [tafia/calamine#270]
thread 'main' panicked at 'range end index 2 out of range for slice of length 0', library\core\src\slice\index.rs:73:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584   
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142  
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\slice\index.rs:73 
   3: core::ops::function::FnOnce::call_once<never$ (*)(usize,usize),tuple$<usize,usize> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\ops\function.rs:248
   4: core::intrinsics::const_eval_select<tuple$<usize,usize>,never$ (*)(usize,usize),never$ (*)(usize,usize),never$>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\intrinsics.rs:2376   5: core::slice::index::slice_end_index_len_fail
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\slice\index.rs:67 
   6: core::slice::index::impl$3::index<u8>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\slice\index.rs:304   7: core::slice::index::impl$4::index<u8>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\slice\index.rs:351   8: core::slice::index::impl$0::index<u8,core::ops::range::RangeTo<usize> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\slice\index.rs:18 
   9: calamine::utils::read_u16
             at C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\calamine-0.18.0\src\utils.rs:34
  10: calamine::xls::read_rich_extended_string
8.0\src\xls.rs:579
  11: calamine::xls::parse_sst
             at C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\calamine-0.18.0\src\xls.rs:538
  12: calamine::xls::Xls<std::io::buffered::bufreader::BufReader<std::fs::File> >::parse_workbook<std::io::buffered::bufreader::BufReader<std::fs::File> >
             at C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\calamine-0.18.0\src\xls.rs:234
  13: calamine::xls::impl$2::new<std::io::buffered::bufreader::BufReader<std::fs::File> >
             at C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\calamine-0.18.0\src\xls.rs:151
  14: calamine::open_workbook<calamine::xls::Xls<std::io::buffered::bufreader::BufReader<std::fs::File> >,ref$<alloc::string::String> >
             at C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\calamine-0.18.0\src\lib.rs:203
  15: calamine::auto::open_workbook_auto<alloc::string::String>
             at C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\calamine-0.18.0\src\auto.rs:28
  16: rcpick::utils::cell_data
             at .\utils.rs:6
  17: rcpick::main
             at .\main.rs:16
  18: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

rustc 1.63.0 (4b91a6ea7 2022-08-08)
panic :    let mut workbook = open_workbook_auto("empty.xls").expect("Cannot open file");
 open file: [empty.xls](https://github.com/tafia/calamine/files/9622224/empty.xls)

**Comment by 1991766703** [comment]
Thank you! It is worked now.
